[build]
  command = "npm run build"  # Comando para construir tu aplicación Express.js si es necesario
  functions = "functions"    # Directorio donde estarán tus funciones serverless

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

