[build]
  command = "npm run build"  # Comando para construir tu aplicación Express.js si es necesario
  functions = "functions"    # Directorio donde estarán tus funciones serverless

[[plugins]]
  package = "@netlify/plugin-functions-install"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200